const MONGODB_CONNECTION_STRING = process.env.MONGODB_CONNECTION_STRING;
const JWT_TOKEN_SECRET = process.env.JWT_TOKEN_SECRET;

module.exports = {
  MONGODB_CONNECTION_STRING,
  JWT_TOKEN_SECRET,
};
