const MONGODB_CONNECTION_STRING = process.env.MONGODB_CONNECTION_STRING;
const JWT_TOKEN_SECRET = process.env.JWT_TOKEN_SECRET;
const HASH_SALT_ROUNDS = process.env.HASH_SALT_ROUNDS;

module.exports = {
  MONGODB_CONNECTION_STRING,
  JWT_TOKEN_SECRET,
  HASH_SALT_ROUNDS,
};
